---
title: "13.2 Classes"
output: html_notebook
---
 
 
```{r}
# Create and assign class in one step
foo <- structure(list(), class = "foo")

# Create, then set class
foo <- list()
class(foo) <- "foo"

# Determine class of foo
class(foo)

inherits(foo, "foo")
```
```{r}
# create a linear model
mod <- lm(log(mpg) ~ log(disp), data = mtcars)
class(mod)

print(mod)

# turn it into a data frame (?!)
class(mod) <- "data.frame"

mod

```

```{r constructors}
new_Date <- function(x){
  stopifnot(is.double(x))
  structure(x, class = "Date")
}
new_Date(c(-1, 0, 1))

new_POSIXct  <- function(x, tzone = "") {
  stopifnot(is.double(x))
  stopifnot(is.character(tzone),length(tzone) == 1)
  
  structure(x,
    class = c("POSIXct", "POSIXt"),
    tzone = tzone
  )
}

new_POSIXct(1)

new_POSIXct(1, tzone = "UTC")
```

```{r validators}
new_factor <- function(x, levels) {
  stopifnot(is.integer(x))
  stopifnot(is.character(levels))
  
  structure(
    x,
    levels = levels,
    class = "factor"
  )
}

#new_factor(1:5, "a")
#new_factor(0:1, "a")


validate_factor <- function(x) {
  values <- unclass(x)
  levels <- attr(x, "levels")
  
  if (!all(!is.na(values) & values > 0)) {
    stop(
      "All `x` values must be non-missing and greater than zero",
      call. = FALSE
    )
  }
  
  if (length(levels) < max(values)) {
    stop(
      "There must be at least as many `levels` as possible values in `x`",
      call. = FALSE
    )
  }
  
  x
}

#validate_factor(new_factor(1:5, "a"))

#validate_factor(new_factor(0:1, "a"))

```



